//! API key authentication.
//!
//! Allows third-party integrations to authenticate with `X-Api-Key: skp_...`
//! instead of a short-lived JWT.  Keys are generated by farmers in the
//! dashboard, SHA-256 hashed before storage, and never retrievable again.
//!
//! Axum extractor: `ApiKeyClaims` — extract and validate the key in one step.
//! On success, `last_used_at` is bumped in the background (non-blocking).

use crate::auth::jwt::{Claims, Role};
use crate::error::AppError;
use crate::state::SharedState;
use axum::{async_trait, extract::FromRequestParts, http::request::Parts};
use sha2::{Digest, Sha256};
use uuid::Uuid;

/// SHA-256 hash of an API key, returned as a lowercase hex string.
pub fn hash_key(raw: &str) -> String {
    let mut hasher = Sha256::new();
    hasher.update(raw.as_bytes());
    hex::encode(hasher.finalize())
}

/// Axum extractor that validates an `X-Api-Key` header and returns the
/// associated `Claims` (with the farmer's identity and role).
///
/// Returns 401 if the header is absent or the key is invalid / revoked.
#[allow(dead_code)]
pub struct ApiKeyClaims(pub Claims);

#[async_trait]
impl FromRequestParts<SharedState> for ApiKeyClaims {
    type Rejection = AppError;

    async fn from_request_parts(
        parts: &mut Parts,
        state: &SharedState,
    ) -> Result<Self, Self::Rejection> {
        let raw = parts
            .headers
            .get("x-api-key")
            .and_then(|v| v.to_str().ok())
            .ok_or_else(|| AppError::Unauthorized("X-Api-Key header missing".into()))?;

        if !raw.starts_with("skp_") {
            return Err(AppError::Unauthorized("Invalid API key format".into()));
        }

        let hash = hash_key(raw);

        #[derive(sqlx::FromRow)]
        struct KeyRow {
            id: Uuid,
            farmer_id: Uuid,
            scopes: Vec<String>,
        }

        let row: Option<KeyRow> = sqlx::query_as(
            "SELECT id, farmer_id, scopes
             FROM api_keys
             WHERE key_hash = $1 AND revoked_at IS NULL",
        )
        .bind(&hash)
        .fetch_optional(&state.db)
        .await
        .map_err(|e| AppError::Internal(e.into()))?;

        let row = row.ok_or_else(|| AppError::Unauthorized("API key invalid or revoked".into()))?;

        // Bump last_used_at in the background — never block the request for this.
        let pool = state.db.clone();
        let key_id = row.id;
        tokio::spawn(async move {
            let _ = sqlx::query("UPDATE api_keys SET last_used_at = NOW() WHERE id = $1")
                .bind(key_id)
                .execute(&pool)
                .await;
        });

        // Build Claims matching the farmer's identity.
        // exp is far future (10 years) — actual expiry is enforced by revoked_at.
        let exp = (chrono::Utc::now() + chrono::Duration::days(3650)).timestamp() as usize;
        let iat = chrono::Utc::now().timestamp() as usize;

        // Derive role from scopes: if any write scope is present, treat as Farmer;
        // otherwise still Farmer but handlers may check scopes separately.
        let _scopes = row.scopes; // available for future scope-based authz

        let claims = Claims {
            sub: row.farmer_id.to_string(),
            role: Role::Farmer,
            farmer_id: Some(row.farmer_id),
            exp,
            iat,
        };

        Ok(ApiKeyClaims(claims))
    }
}
